/**
 * Canonical university + course catalogue — the single source of truth for the
 * destructive prisma/seed.ts AND the additive scripts/add-catalog.ts.
 * Extracted verbatim from the seed; see add-catalog.ts for the upsert defaults.
 */

export type CourseSeed = {
  slug: string
  title: string
  subtitle: string
  level: string
  mode: string
  stream: string
  durationYears: number
  feePerYear: number
  originalFee?: number
  university: string
  about: string
  eligibility: string
  highlights: string[]
  skills: string[]
  recruiters: string[]
  rating: number
  reviews: number
  featured?: boolean
  hasLiveClass?: boolean
  hasPlacement?: boolean
}


export const UNIVERSITIES = [
  {
    slug: 'amity-university-online',
    highlights: [
      'UGC-entitled degrees — valid for jobs, higher study and government exams',
      'NAAC A+ accredited, with a QS-ranked online MBA',
      'AICTE-approved and WES-recognised for study abroad',
      '50,000+ online learners across 200+ programmes',
      'Live and recorded classes, e-library and placement support',
    ],
    name: 'Amity University Online',
    shortName: 'Amity',
    about:
      'Amity University Online is one of India’s leading online education platforms offering industry-relevant programs with world-class faculty, advanced learning tools and excellent placement support. Its degrees carry the same weight as on-campus programs and are recognised by employers across India and abroad.',
    estYear: 2005,
    naacGrade: 'A+',
    approvals: ['UGC Entitled', 'NAAC A+', 'AICTE Approved', 'WES Recognised'],
    rating: 4.5,
    reviews: 12345,
    students: 50000,
    programs: 200,
    city: 'Noida',
    state: 'Uttar Pradesh',
    featured: true,
  },
  {
    slug: 'manipal-university-online',
    highlights: [
      'Seven decades of academic legacy (established 1953)',
      'UGC-entitled, NAAC A+ and AICTE-approved online degrees',
      'Taught by the same faculty as the on-campus programmes',
      '42,000+ online learners across 160+ programmes',
      'Dedicated placement cell and industry-aligned curriculum',
    ],
    name: 'Manipal University Online',
    shortName: 'Manipal',
    about:
      'Manipal University Online brings seven decades of academic excellence to the digital classroom. Programs are designed with industry partners, taught by the same faculty who teach on campus, and backed by a dedicated placement cell.',
    estYear: 1953,
    naacGrade: 'A+',
    approvals: ['UGC Entitled', 'NAAC A+', 'AICTE Approved'],
    rating: 4.4,
    reviews: 9820,
    students: 42000,
    programs: 160,
    city: 'Manipal',
    state: 'Karnataka',
    featured: true,
  },
  {
    slug: 'chandigarh-university-online',
    highlights: [
      'UGC-entitled, NAAC A+ and AICTE-approved online degrees',
      'Industry-designed curriculum with live projects',
      '35,000+ online learners across 120+ programmes',
      'Strong placement record with 900+ recruiting partners',
      'Flexible online examinations with remote proctoring',
    ],
    name: 'Chandigarh University Online',
    shortName: 'Chandigarh',
    about:
      'Chandigarh University Online delivers flexible, career-focused degrees with live mentoring, recorded lectures and a strong placement network of 900+ recruiters.',
    estYear: 2012,
    naacGrade: 'A+',
    approvals: ['UGC Entitled', 'NAAC A+', 'AICTE Approved'],
    rating: 4.6,
    reviews: 7640,
    students: 35000,
    programs: 120,
    city: 'Mohali',
    state: 'Punjab',
    featured: true,
  },
  {
    slug: 'lpu-online',
    highlights: [
      'NAAC A++ accredited and UGC-entitled',
      'Among the largest placement drives in North India',
      'Global exposure with industry-led projects',
      '48,000+ online learners across 140+ programmes',
      'AICTE-approved, with live and recorded classes',
    ],
    name: 'LPU Online',
    shortName: 'LPU',
    about:
      'Lovely Professional University Online offers UGC-entitled degrees with global exposure, industry projects and one of the largest placement drives in North India.',
    estYear: 2005,
    naacGrade: 'A++',
    approvals: ['UGC Entitled', 'NAAC A++', 'AICTE Approved'],
    rating: 4.6,
    reviews: 11200,
    students: 48000,
    programs: 140,
    city: 'Jalandhar',
    state: 'Punjab',
    featured: true,
  },
  {
    slug: 'jain-university-online',
    highlights: [
      'NAAC A++ accredited and UGC-entitled degrees',
      'Strong focus on management and entrepreneurship',
      '28,000+ online learners across 95+ programmes',
      'Bengaluru-based, with startup and industry links',
      'Live classes, mentorship and placement support',
    ],
    name: 'Jain University Online',
    shortName: 'Jain',
    about:
      'Jain (Deemed-to-be University) Online focuses on entrepreneurship, technology and management education with immersive digital classrooms and industry certifications bundled into the degree.',
    estYear: 1990,
    naacGrade: 'A++',
    approvals: ['UGC Entitled', 'NAAC A++', 'AICTE Approved'],
    rating: 4.5,
    reviews: 6430,
    students: 28000,
    programs: 95,
    city: 'Bengaluru',
    state: 'Karnataka',
    featured: true,
  },
  {
    slug: 'dy-patil-university-online',
    highlights: [
      'UGC-entitled and NAAC A+ accredited',
      'Management and healthcare-focused online programmes',
      '21,000+ online learners across 70+ programmes',
      'Industry-aligned curriculum with live sessions',
      'Dedicated academic and career support',
    ],
    name: 'DY Patil University Online',
    shortName: 'DY Patil',
    about:
      'DY Patil University Online blends management and healthcare-adjacent programs with a practice-first curriculum and strong corporate tie-ups in Western India.',
    estYear: 2002,
    naacGrade: 'A+',
    approvals: ['UGC Entitled', 'NAAC A+'],
    rating: 4.3,
    reviews: 4180,
    students: 21000,
    programs: 70,
    city: 'Navi Mumbai',
    state: 'Maharashtra',
    featured: true,
  },
  {
    slug: 'ignou',
    highlights: [
      'India’s largest university — 3 lakh+ learners',
      'UGC-DEB approved and NAAC A++ accredited',
      '250+ programmes across nearly every discipline',
      'Among the most affordable recognised degrees',
      'Nationwide network of regional and exam centres',
    ],
    name: 'IGNOU',
    shortName: 'IGNOU',
    about:
      'Indira Gandhi National Open University is India’s largest open university, offering affordable, UGC-DEB approved distance programs to learners in every district of the country.',
    estYear: 1985,
    naacGrade: 'A++',
    approvals: ['UGC-DEB Approved', 'NAAC A++'],
    rating: 4.5,
    reviews: 20140,
    students: 300000,
    programs: 250,
    city: 'New Delhi',
    state: 'Delhi',
    featured: true,
  },
]

export const COURSES: CourseSeed[] = [
  {
    slug: 'online-bba-digital-marketing',
    title: 'Online BBA in Digital Marketing',
    subtitle: 'Specialise in digital marketing, social media, SEO, content & analytics.',
    level: 'UG',
    mode: 'ONLINE',
    stream: 'MANAGEMENT',
    durationYears: 3,
    feePerYear: 55000,
    originalFee: 70000,
    university: 'manipal-university-online',
    about:
      'This Online BBA in Digital Marketing is designed to provide a strong foundation in management along with advanced digital marketing skills. Learn from industry experts and work on real-world projects covering SEO, social media, content strategy, analytics and paid advertising to build high-demand skills for the digital world.',
    eligibility: '10+2 or equivalent from a recognised board with minimum 50% marks',
    highlights: [
      'UGC Entitled Degree',
      'Industry-Oriented Curriculum',
      'Live Classes & Recorded Lectures',
      'Assignments & Case Studies',
      'Internship Opportunities',
      'Placement Assistance',
    ],
    skills: [
      'Digital Marketing', 'SEO & SEM', 'Social Media Marketing', 'Google Analytics',
      'Content Marketing', 'Email Marketing', 'Brand Management', 'Web Analytics',
    ],
    recruiters: ['Deloitte', 'Amazon', 'Infosys', 'HDFC Bank', 'Wipro', 'TCS'],
    rating: 4.5,
    reviews: 2345,
    featured: true,
  },
  {
    slug: 'bachelor-of-business-administration',
    title: 'Bachelor of Business Administration (BBA)',
    subtitle: 'Build a strong foundation in business management, leadership & entrepreneurship.',
    level: 'UG',
    mode: 'ONLINE',
    stream: 'MANAGEMENT',
    durationYears: 3,
    feePerYear: 45000,
    originalFee: 60000,
    university: 'amity-university-online',
    about:
      'A comprehensive undergraduate program covering the full breadth of business administration — accounting, marketing, human resources, operations and strategy — with a capstone entrepreneurship project in the final year.',
    eligibility: '10+2 or equivalent from a recognised board',
    highlights: [
      'UGC Entitled Degree', 'AI-Powered Learning Support', 'Placement Assistance',
      'Flexible EMI Options', 'Industry Case Studies',
    ],
    skills: ['Business Strategy', 'Financial Accounting', 'Marketing Management', 'Operations', 'Leadership'],
    recruiters: ['Deloitte', 'ICICI Bank', 'Amazon', 'Accenture', 'Kotak'],
    rating: 4.6,
    reviews: 3110,
    featured: true,
  },
  {
    slug: 'bba-international-business',
    title: 'BBA in International Business',
    subtitle: 'Learn global business practices, international trade, finance & cross-cultural management.',
    level: 'UG',
    mode: 'ONLINE',
    stream: 'MANAGEMENT',
    durationYears: 3,
    feePerYear: 50000,
    originalFee: 65000,
    university: 'lpu-online',
    about:
      'Designed for learners who want a career spanning borders. Covers export-import documentation, foreign exchange, global supply chains and cross-cultural negotiation with live projects on real trade scenarios.',
    eligibility: '10+2 or equivalent with minimum 50% marks',
    highlights: ['UGC Entitled Degree', 'Global Exposure Modules', 'Placement Assistance', 'Live Mentoring'],
    skills: ['International Trade', 'Forex', 'Global Supply Chain', 'Cross-Cultural Management', 'Export Documentation'],
    recruiters: ['Maersk', 'DHL', 'Infosys', 'Wipro', 'Reliance'],
    rating: 4.4,
    reviews: 1580,
    featured: true,
  },
  {
    slug: 'bba-finance-accounting',
    title: 'BBA in Finance & Accounting',
    subtitle: 'Focus on financial management, accounting, banking and investment strategies.',
    level: 'UG',
    mode: 'DISTANCE',
    stream: 'COMMERCE',
    durationYears: 3,
    feePerYear: 18000,
    originalFee: 24000,
    university: 'ignou',
    about:
      'An affordable, UGC-DEB approved distance program building deep competence in financial accounting, corporate finance, taxation and investment analysis, with printed and digital study material.',
    eligibility: '10+2 or equivalent from a recognised board',
    highlights: ['UGC-DEB Approved', 'Printed + Digital Study Material', 'Exam Support', 'Lowest Fees'],
    skills: ['Financial Accounting', 'Corporate Finance', 'Taxation', 'Investment Analysis', 'Auditing'],
    recruiters: ['SBI', 'HDFC Bank', 'Deloitte', 'EY', 'PwC'],
    rating: 4.5,
    reviews: 4210,
    featured: true,
    hasLiveClass: false,
  },
  {
    slug: 'online-mba-business-analytics',
    title: 'Online MBA in Business Analytics',
    subtitle: 'Turn data into decisions with Python, SQL, visualisation and predictive modelling.',
    level: 'PG',
    mode: 'ONLINE',
    stream: 'MANAGEMENT',
    durationYears: 2,
    feePerYear: 110000,
    originalFee: 140000,
    university: 'amity-university-online',
    about:
      'A two-year postgraduate program that pairs core MBA fundamentals with a rigorous analytics track — Python, SQL, Power BI, statistics and machine learning applied to real business problems.',
    eligibility: 'Bachelor’s degree in any discipline with minimum 50% marks',
    highlights: [
      'UGC Entitled Degree', 'Capstone Analytics Project', 'Industry Certifications Included',
      'Live Classes & Recorded Lectures', 'Dedicated Placement Cell',
    ],
    skills: ['Python', 'SQL', 'Power BI', 'Statistics', 'Machine Learning', 'Business Strategy'],
    recruiters: ['Deloitte', 'Amazon', 'Flipkart', 'Accenture', 'ZS Associates'],
    rating: 4.7,
    reviews: 1890,
    featured: true,
  },
  {
    slug: 'online-mca',
    title: 'Online MCA (Master of Computer Applications)',
    subtitle: 'Advanced software engineering, cloud, and full-stack development.',
    level: 'PG',
    mode: 'ONLINE',
    stream: 'IT',
    durationYears: 2,
    feePerYear: 75000,
    originalFee: 95000,
    university: 'chandigarh-university-online',
    about:
      'Build production-grade software skills across full-stack development, cloud infrastructure, DBMS and system design, with a capstone deployed to a live environment.',
    eligibility: 'Bachelor’s degree with Mathematics at 10+2 or graduation level',
    highlights: ['UGC Entitled Degree', 'Cloud Lab Access', 'Capstone Project', 'Placement Assistance'],
    skills: ['Java', 'Full Stack Development', 'Cloud Computing', 'DBMS', 'System Design'],
    recruiters: ['TCS', 'Infosys', 'Cognizant', 'Wipro', 'Tech Mahindra'],
    rating: 4.5,
    reviews: 2240,
  },
  {
    slug: 'online-bca',
    title: 'Online BCA (Bachelor of Computer Applications)',
    subtitle: 'Programming, web development, databases and computing fundamentals.',
    level: 'UG',
    mode: 'ONLINE',
    stream: 'IT',
    durationYears: 3,
    feePerYear: 42000,
    originalFee: 55000,
    university: 'jain-university-online',
    about:
      'A hands-on undergraduate computing degree. Start from programming fundamentals and progress to web development, databases and software engineering, building a portfolio of deployed projects along the way.',
    eligibility: '10+2 in any stream from a recognised board',
    highlights: [
      'UGC Entitled Degree', 'Hands-on Coding Labs', 'Industry Certifications',
      'Portfolio Projects', 'Placement Assistance',
    ],
    skills: ['C & C++', 'Python', 'Web Development', 'DBMS', 'Data Structures', 'Git'],
    recruiters: ['Infosys', 'Zoho', 'Mindtree', 'Capgemini', 'HCL'],
    rating: 4.4,
    reviews: 1975,
    featured: true,
  },
  {
    slug: 'bcom-hons-online',
    title: 'B.Com (Hons) Online',
    subtitle: 'Commerce, taxation and corporate law with a professional-exam aligned syllabus.',
    level: 'UG',
    mode: 'ONLINE',
    stream: 'COMMERCE',
    durationYears: 3,
    feePerYear: 38000,
    originalFee: 48000,
    university: 'dy-patil-university-online',
    about:
      'An honours commerce degree aligned to CA/CS foundation syllabi, covering advanced accounting, GST, corporate law and financial reporting.',
    eligibility: '10+2 with Commerce or equivalent',
    highlights: ['UGC Entitled Degree', 'CA/CS Aligned Syllabus', 'Exam Preparation Support'],
    skills: ['Advanced Accounting', 'GST', 'Corporate Law', 'Financial Reporting', 'Cost Accounting'],
    recruiters: ['EY', 'KPMG', 'Grant Thornton', 'HDFC Bank'],
    rating: 4.3,
    reviews: 1320,
  },
  {
    slug: 'mcom-online',
    title: 'M.Com Online',
    subtitle: 'Postgraduate commerce with specialisation in finance and taxation.',
    level: 'PG',
    mode: 'DISTANCE',
    stream: 'COMMERCE',
    durationYears: 2,
    feePerYear: 16000,
    originalFee: 20000,
    university: 'ignou',
    about:
      'A postgraduate commerce program for working professionals, focused on advanced financial management, research methodology and applied taxation.',
    eligibility: 'B.Com or equivalent bachelor’s degree',
    highlights: ['UGC-DEB Approved', 'Lowest Fees', 'Study Material Included'],
    skills: ['Financial Management', 'Research Methods', 'Taxation', 'Managerial Economics'],
    recruiters: ['SBI', 'LIC', 'Deloitte', 'PwC'],
    rating: 4.4,
    reviews: 2870,
    hasLiveClass: false,
  },
  {
    slug: 'ma-english-online',
    title: 'Online MA in English',
    subtitle: 'Literature, linguistics and critical theory for educators and writers.',
    level: 'PG',
    mode: 'DISTANCE',
    stream: 'ARTS',
    durationYears: 2,
    feePerYear: 14000,
    originalFee: 18000,
    university: 'ignou',
    about:
      'Explore British, American and Indian writing in English alongside literary theory and linguistics — a strong base for teaching, publishing, UGC-NET and civil services preparation.',
    eligibility: 'Bachelor’s degree in any discipline',
    highlights: ['UGC-DEB Approved', 'NET/JRF Aligned', 'Affordable Fees'],
    skills: ['Literary Criticism', 'Linguistics', 'Academic Writing', 'Comparative Literature'],
    recruiters: ['Kendriya Vidyalaya', 'Pearson', 'Byju’s', 'Scholastic'],
    rating: 4.4,
    reviews: 1640,
    hasLiveClass: false,
    hasPlacement: false,
  },
  {
    slug: 'btech-cse-regular',
    title: 'B.Tech in Computer Science & Engineering',
    subtitle: 'On-campus engineering degree with labs, internships and campus placements.',
    level: 'UG',
    mode: 'REGULAR',
    stream: 'ENGINEERING',
    durationYears: 4,
    feePerYear: 160000,
    originalFee: 185000,
    university: 'lpu-online',
    about:
      'A four-year on-campus engineering program with specialisation tracks in AI, cybersecurity and cloud, backed by one of India’s largest campus placement drives.',
    eligibility: '10+2 with Physics, Chemistry and Mathematics; valid entrance score',
    highlights: ['AICTE Approved', 'On-Campus Labs', 'Internship Guaranteed', 'Campus Placements'],
    skills: ['Data Structures', 'Operating Systems', 'Machine Learning', 'Cybersecurity', 'Cloud'],
    recruiters: ['Microsoft', 'Amazon', 'Google', 'Cisco', 'Bosch'],
    rating: 4.6,
    reviews: 5210,
  },
  {
    slug: 'ba-llb-integrated',
    title: 'BA LLB (Integrated Law)',
    subtitle: 'Five-year integrated law degree with moot courts and internships.',
    level: 'INTEGRATED',
    mode: 'REGULAR',
    stream: 'LAW',
    durationYears: 5,
    feePerYear: 125000,
    originalFee: 145000,
    university: 'chandigarh-university-online',
    about:
      'A Bar Council recognised integrated law program combining humanities with core legal study, moot court practice and mandatory chamber internships.',
    eligibility: '10+2 with minimum 50% marks; CLAT/entrance score preferred',
    highlights: ['Bar Council Recognised', 'Moot Court Training', 'Chamber Internships'],
    skills: ['Constitutional Law', 'Criminal Law', 'Corporate Law', 'Legal Research', 'Advocacy'],
    recruiters: ['Khaitan & Co', 'AZB & Partners', 'Trilegal', 'Cyril Amarchand'],
    rating: 4.5,
    reviews: 980,
  },
  {
    slug: 'diploma-digital-marketing',
    title: 'Diploma in Digital Marketing',
    subtitle: 'One-year practitioner diploma covering paid ads, SEO and analytics.',
    level: 'DIPLOMA',
    mode: 'ONLINE',
    stream: 'MANAGEMENT',
    durationYears: 1,
    feePerYear: 28000,
    originalFee: 36000,
    university: 'amity-university-online',
    about:
      'A fast, practical diploma for career switchers. Run live ad campaigns, audit real websites and finish with a portfolio and Google/Meta certification preparation.',
    eligibility: '10+2 or equivalent; working professionals welcome',
    highlights: ['1-Year Fast Track', 'Live Campaign Projects', 'Certification Prep', 'Weekend Batches'],
    skills: ['Google Ads', 'Meta Ads', 'SEO', 'Analytics', 'Copywriting'],
    recruiters: ['Dentsu', 'Ogilvy', 'Zomato', 'Swiggy'],
    rating: 4.4,
    reviews: 860,
  },
  {
    slug: 'certificate-data-science',
    title: 'Certificate in Data Science',
    subtitle: 'Short-format certificate in Python, statistics and machine learning.',
    level: 'CERTIFICATE',
    mode: 'PART_TIME',
    stream: 'IT',
    durationYears: 1,
    feePerYear: 22000,
    originalFee: 30000,
    university: 'jain-university-online',
    about:
      'An evening-batch certificate for working professionals moving into data roles. Python, pandas, statistics, visualisation and a supervised-learning capstone.',
    eligibility: 'Graduation in any discipline; basic mathematics recommended',
    highlights: ['Evening Batches', 'Capstone Project', 'Industry Mentors', 'Placement Support'],
    skills: ['Python', 'pandas', 'Statistics', 'scikit-learn', 'Data Visualisation'],
    recruiters: ['Fractal', 'Mu Sigma', 'TCS', 'Accenture'],
    rating: 4.5,
    reviews: 640,
  },
]
